#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Al Fischer

# Short bio or description (displayed in the header)
description: Instrumentation Specialist

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /assets/img/mountainHaze.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  email: dfischer@wcu.edu
  flickr: photos/alphonse-fischer
  github: alphonse
  instagram: alphonse.fisch
  linkedin:
  rss: anything
  twitter:
  youtube: # channel/<your_long_string> or user/<user-name>



# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-74190135-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://alphonse.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

navigation:
  - title: Homepage
    url: /#
  - title: about
    url: /about
  - title: contact
    url: /contact
  - title: curriculum vitae
    url: /curriculum-vitae
  - title: projects
    url: /projects
navigation-370:
  - title:  
    url: /#
    icon: fa-user-circle
  - title: 370 Main Page
    url: /chem370/#
    icon: fa-home
  - title: Syllabus
    url: /chem370/syllabus
    icon: fa-scroll
  - title: Schedule
    url: /chem370/schedule
    icon: fa-calendar-alt  
  - title: Lab
    url: /chem370/lab-manual
    icon: fa-vial  
  - title: Lectures
    url: /chem370/lectures
    icon: fa-chalkboard-teacher
  - title: R
    url: /chem370/data-processing
    icon: fa-chart-line 
  - title: Writing
    url: /chem370/writing
    icon: fa-edit  
  - title: Submissions
    url: /chem370/submissions
    icon: fa-paper-plane    
navigation-689:
  - title:  
    url: /#
    icon: fa-user-circle
  - title: 689 Main Page
    url: /chem689/#
    icon: fa-home
  - title: Syllabus
    url: /chem689/syllabus
    icon: fa-scroll
  - title: Notebooks
    url: /chem689/notebooks
    icon: fa-edit    
